// <auto-generated />
using Lesson3_CNLTWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson3_CNLTWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619043724_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lesson3_CNLTWeb.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.RoomImage_BIT240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages_BIT240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room101-1",
                            IsThumbnail = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room101-2",
                            IsThumbnail = false,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room102-1",
                            IsThumbnail = true,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room102-2",
                            IsThumbnail = false,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room201-1",
                            IsThumbnail = true,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room201-2",
                            IsThumbnail = false,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room202-1",
                            IsThumbnail = true,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=Room202-2",
                            IsThumbnail = false,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=VIP1-1",
                            IsThumbnail = true,
                            RoomId = 5
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff&text=VIP1-2",
                            IsThumbnail = false,
                            RoomId = 5
                        });
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.RoomType_BIT240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes_BIT240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phòng Trọ Sinh Viên"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chung Cư Mini"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phòng Studio Cao Cấp"
                        });
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.Room_BIT240041", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms_BIT240041");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 20.5,
                            IsAvailable = true,
                            Name = "Phòng 101",
                            Price = 1500000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 25.0,
                            IsAvailable = false,
                            Name = "Phòng 102",
                            Price = 1800000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Area = 35.0,
                            IsAvailable = true,
                            Name = "Phòng 201",
                            Price = 3500000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Area = 40.0,
                            IsAvailable = true,
                            Name = "Phòng 202",
                            Price = 3800000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Area = 55.5,
                            IsAvailable = true,
                            Name = "Phòng VIP 1",
                            Price = 5500000m,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.RoomImage_BIT240041", b =>
                {
                    b.HasOne("Lesson3_ORM_BookManagement.Models.Room_BIT240041", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.Room_BIT240041", b =>
                {
                    b.HasOne("Lesson3_ORM_BookManagement.Models.RoomType_BIT240041", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.RoomType_BIT240041", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Lesson3_ORM_BookManagement.Models.Room_BIT240041", b =>
                {
                    b.Navigation("RoomImages");
                });
#pragma warning restore 612, 618
        }
    }
}
